### ISSUE TITLE
Implement auto route for tun inbound

### ISSUE THREAD

**Issue by ibigbug** [Watfaq/clash-rs#559]
## Tenets

* clash-rs should handle traffic on given routes when tun inbound is enabled
* users should be able to tell the routes they want to proxy over tun
* should work on Windows/Linux/macOS
* we should try our best to resolve routes failures and give as much details when things don't work

## Work Items
- [ ] #228 
- [ ] #456 
- [x] #541 
- [x] #552 
- [x] #396
- [ ] #579 
- [x] platform
    - [x] Windows
      * doesn't work - https://learn.microsoft.com/en-us/windows/win32/api/rtmv2/nf-rtmv2-rtmaddnexthop
      * use built in command instead
    - [x] Linux - https://www.wireguard.com/netns/ either fwmark or ns
    - [x] macOS - assumes `route` command is builtin
- [ ] ipv6 - blocked by #579 

## Example config

```yaml
tun:
  enable: true
  device-id: "dev://utun1989"
  routes:
    - 0.0.0.0/1
    - 128.0.0.0/1
```

## Implementation

- [x] Windows - https://github.com/Watfaq/clash-rs/pull/561
- [x] macOS - #592 
- [x] Linux - #594
